### ISSUE TITLE
Good bot but...

### ISSUE THREAD

**Issue by spix18** [lhunt364/d2-fishing-bot#1]
First of i gotta thank you for the bot , its working as intended but i would like to request some features to be added:

1- anti afk is a must since this is a bot.
2- we need to have the ability to changes keybinding for "Start" and "Stop" and "coord1" and "coord2"
3- tracking of how much fish we fished and maybe what kind of fish quality too during that pond session ?

**Comment by lhunt364** [comment]
Thank you for the feedback. 

You're right, anti afk is necessary, and I'll add that soon. It's possible to change the key bindings, but it requires you to manually open the config.properties file, so I plan on adding that functionality into the bot window. Tracking fish caught during each pond session is an interesting idea, I think I have an idea of how it could be implemented, so I may add it in a future update.

Thank you again for using the bot, glad to hear it's working!
